language: nix

matrix:
  fast_finish: true
  include:
    - env: GHCVER=ghc802
    - env: GHCVER=ghc821

before_install:
 - nix-channel --list
 - nix-channel --update

script:
 - nix-build -A envy --argstr compiler $GHCVER
